services:
  postgres:
    image: postgres:16
    container_name: decorar_postgres
    environment:
      POSTGRES_DB: decorar_sem_gastar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"